### ISSUE TITLE
Viewing images in Gwenview

### ISSUE THREAD

**Issue by FreeSlave** [panzi/qvtf#1]
It seems like Gwenview requires mime type to be installed to view .vtf images.
Even 'Open with' Gwenview does not help. Kolourpaint shows the image, but vtf is still is not in the list of supported formats.

The solution is to install mime type. Here's XML description (I wrote it on my own):

```
<?xml version="1.0" encoding="utf-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
	<mime-type type="image/x-vtf">
		<comment>Valve Texture Format</comment>
		<glob pattern="*.vtf"/>
		<magic priority="60">
			<match value="0x00465456" type="little32" offset="0"/>
		</magic>
	</mime-type>
</mime-info>
```

It should be installed to specific location on system (/usr/share/mime/packages) and then get update-mime-database called. It can be done with help of SharedMimeInfo package for CMake.

You can look how it's done in my qt plugin (made for half-life sprites) https://bitbucket.org/FreeSlave/qt-sprite-image-plugin

**Comment by FreeSlave** [comment]
By the way it looks like VTF is already registered by IANA as [vnd.valve.source.texture](http://www.iana.org/assignments/media-types/image/vnd.valve.source.texture). We can use it instead of x-vtf or just add alias to description.

**Comment by panzi** [comment]
You're right. Care to make a pull request? :)
